credentials:
  usernames:
    nwarshak:
      email: warshanj@mail.uc.edu
      name: Nick Warshak
      password: '$2b$12$8WxognREFrh80n9KOy7z/.IYNqJsoP6IyMEuKvQCBGv9iVCsGCeRO'
    kiamanager:
      email: managers@jakesweeney.com
      name: Kia Manager
      password: '$2b$12$iJ683yzFiy1MLdtT1usktu9yHlIhVjvle6o0Xka4MHCvZTW13p/FO'
cookie:
  expiry_days: 30
  key: kia_dashboard_secret_key
  name: kia_auth_cookie
preauthorized:
  emails:
    - nwarshak@uc.edu