SUPABASE_URL = "https://xnbwihxbgjwncgcpqhdh.supabase.co"
SUPABASE_KEY = "sb_publishable_2O75i1wgaXgQi4IOtjt_QA_9ainky7v"


SUPABASE_URL = "https://*******************.supabase.co"
SUPABASE_KEY = "*************************************"
